In [58]:
import numpy as np
import pandas as pd
pd.options.display.max_columns = None
import matplotlib.pyplot as plt
import seaborn as sns

In [59]:
data = pd.read_csv("data.csv", header='infer')
data.head(2)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   

   EnvironmentSatisfaction  Gender  HourlyRate  JobInvolvement  JobLevel  \
0                        2  Female          94               3         2   
1                        3    Male          61               2         2   

              JobRole  JobSatisfaction MaritalStatus  MonthlyIncome  \
0     Sales Executive                4        Single           5993   
1  Research Scientist                2       Married           5130   

   MonthlyRate  NumCompaniesWorked Over18 OverTime  PercentSalaryHike  \
0        19479                   8      Y      Yes                 11   
1        24907                   1      Y       No                 23   

   PerformanceRating  RelationshipSatisfaction  StandardHours  \
0                  3                         1             80   
1                  4                         4             80   

   StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                 0                  8                      0   
1                 1                 10                      3   

   WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                1               6                   4   
1                3              10                   7   

   YearsSinceLastPromotion  YearsWithCurrManager  
0                        0                     5  
1                        1                     7

In [60]:
y = data.iloc[:,1]

In [61]:
data.drop(["Attrition", "EmployeeCount", "EmployeeNumber"], axis=1, inplace=True)
data.head(2)

Age     BusinessTravel  DailyRate              Department  \
0   41      Travel_Rarely       1102                   Sales   
1   49  Travel_Frequently        279  Research & Development   

   DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                 1          2  Life Sciences                        2   
1                 8          1  Life Sciences                        3   

   Gender  HourlyRate  JobInvolvement  JobLevel             JobRole  \
0  Female          94               3         2     Sales Executive   
1    Male          61               2         2  Research Scientist   

   JobSatisfaction MaritalStatus  MonthlyIncome  MonthlyRate  \
0                4        Single           5993        19479   
1                2       Married           5130        24907   

   NumCompaniesWorked Over18 OverTime  PercentSalaryHike  PerformanceRating  \
0                   8      Y      Yes                 11                  3   
1                   1      Y       No                 23                  4   

   RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                         1             80                 0   
1                         4             80                 1   

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                  8                      0                1               6   
1                 10                      3                3              10   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                        0                     5  
1                   7                        1                     7

In [62]:
orig_columns = pd.get_dummies(data).columns
# orig_columns

In [63]:
X = pd.get_dummies(data, drop_first=True)
# X.columns
X.head(2)

Age  DailyRate  DistanceFromHome  Education  EnvironmentSatisfaction  \
0   41       1102                 1          2                        2   
1   49        279                 8          1                        3   

   HourlyRate  JobInvolvement  JobLevel  JobSatisfaction  MonthlyIncome  \
0          94               3         2                4           5993   
1          61               2         2                2           5130   

   MonthlyRate  NumCompaniesWorked  PercentSalaryHike  PerformanceRating  \
0        19479                   8                 11                  3   
1        24907                   1                 23                  4   

   RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                         1             80                 0   
1                         4             80                 1   

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                  8                      0                1               6   
1                 10                      3                3              10   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
0                   4                        0                     5   
1                   7                        1                     7   

   BusinessTravel_Travel_Frequently  BusinessTravel_Travel_Rarely  \
0                                 0                             1   
1                                 1                             0   

   Department_Research & Development  Department_Sales  \
0                                  0                 1   
1                                  1                 0   

   EducationField_Life Sciences  EducationField_Marketing  \
0                             1                         0   
1                             1                         0   

   EducationField_Medical  EducationField_Other  \
0                       0                     0   
1                       0                     0   

   EducationField_Technical Degree  Gender_Male  JobRole_Human Resources  \
0                                0            0                        0   
1                                0            1                        0   

   JobRole_Laboratory Technician  JobRole_Manager  \
0                              0                0   
1                              0                0   

   JobRole_Manufacturing Director  JobRole_Research Director  \
0                               0                          0   
1                               0                          0   

   JobRole_Research Scientist  JobRole_Sales Executive  \
0                           0                        1   
1                           1                        0   

   JobRole_Sales Representative  MaritalStatus_Married  MaritalStatus_Single  \
0                             0                      0                     1   
1                             0                      1                     0   

   OverTime_Yes  
0             1  
1             0

In [64]:
y = y.map(dict(Yes=1, No=0))
y.head(5)

0    1
1    0
2    1
3    0
4    0
Name: Attrition, dtype: int64

In [65]:
y.describe()

count    1470.000000
mean        0.161224
std         0.367863
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: Attrition, dtype: float64

# Imbalance learning

In [66]:
from imblearn.over_sampling import SMOTE
oversample = SMOTE()
X, y = oversample.fit_resample(X, y)

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [68]:
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg = LogisticRegression(max_iter=10000)

# fit the model with data
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

C:\Users\shekhar\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [69]:
from sklearn import metrics

cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[331,  38],
       [ 46, 325]], dtype=int64)

In [70]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
precision = precision_score(y_test, y_pred)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(y_test, y_pred)
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(y_test, y_pred)
print('F1 score: %f' % f1)

Accuracy: 0.886486
Precision: 0.895317
Recall: 0.876011
F1 score: 0.885559


In [71]:
y_pred_train = logreg.predict(X_train)
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_train, y_pred_train)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
precision = precision_score(y_train, y_pred_train)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(y_train, y_pred_train)
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(y_train, y_pred_train)
print('F1 score: %f' % f1)

Accuracy: 0.900927
Precision: 0.915764
Recall: 0.882831
F1 score: 0.898996


In [72]:
logreg.coef_

array([[ 1.78864683e-03, -3.98870294e-04,  5.49226974e-02,
        -2.18712851e-01, -6.19600522e-01, -2.97068420e-03,
        -7.62112433e-01, -9.53112257e-01, -4.46881726e-01,
         6.81808648e-05,  9.95258141e-06,  1.56323666e-01,
         1.56887814e-02, -8.04428307e-01, -4.74559045e-01,
         2.06977736e-01, -1.04919597e+00, -5.67637084e-02,
        -2.45382553e-01, -5.54959161e-01,  1.34687214e-01,
        -1.43391951e-01,  1.23783066e-01, -1.78259955e-01,
        -6.39545905e-01, -6.92757577e-01, -1.88428916e+00,
        -1.19158751e+00, -1.85786768e+00, -1.11315245e+00,
        -2.21400348e+00, -1.20473368e+00, -7.47104965e-01,
        -3.28237802e-01, -1.31119906e+00, -1.82668711e-01,
        -5.04948556e-01, -7.05372923e-01, -5.22218069e-01,
        -1.07532945e+00, -6.09297786e-01, -4.27761976e-01,
        -1.00697249e+00, -4.11109518e-01,  1.46827617e+00]])

In [73]:
logreg.intercept_

array([0.00291986])

In [84]:
variables = ["Intercept"]+list(X.columns)

In [86]:
df = pd.DataFrame(index=variables)

In [96]:
values = list(logreg.intercept_)+list(logreg.coef_[0])

In [97]:
df["Coefficients"] = values

In [99]:
df.to_clipboard()